Repository anshu-choubey/Tools-for-WhatsApp, pull requests merged in 2024-01, with the labels that each got.

#22 fix navigation drawer send menu
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/whatsapptools/apps/activities/HomeActivity.java
  app/src/main/java/com/whatsapptools/apps/fragments/TextDecoratorFragment.java
Labels: bug, easy, apertre

#23 Readme File
  Kotlin_logo.svg.png
  README.md
  java_language.jpg
Labels: documentation, good first issue, easy, apertre

#30 Update README.md
  README.md
Labels: documentation, easy, apertre

#28 #15 issue solved
  Screenshots_app/Screenshot1.jpg
  Screenshots_app/Screenshot10.jpg
  Screenshots_app/Screenshot11.jpg
  Screenshots_app/Screenshot12.jpg
  Screenshots_app/Screenshot2.jpg
  Screenshots_app/Screenshot3.jpg
  Screenshots_app/Screenshot5.jpg
  Screenshots_app/Screenshot6.jpg
  Screenshots_app/Screenshot7.jpg
  Screenshots_app/Screenshot8.jpg
  Screenshots_app/Screenshot9.jpg
Labels: documentation, easy, apertre

#31 #11 issue solved
  Logo/Logo1.png
  Logo/Logo2.jpeg
Labels: enhancement, easy, apertre
